# Generated by Django 5.0.6 on 2024-05-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_alter_emprestimos_data_devolucao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
